name: Check Merge Conflicts

on: [push, pull_request]

jobs:
  conflict-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Check for merge conflicts
      run: |
        git fetch origin main
        if git merge-tree $(git merge-base HEAD origin/main) HEAD origin/main | grep "<<<<<<<"; then
          echo "Merge conflicts detected!"
          exit 1
        else
          echo "No merge conflicts detected."
        fi
